### ISSUE TITLE
KeyError:'val_loss'

### ISSUE THREAD

**Issue by GuibinChenTHU** [yalickj/load-forecasting-resnet#2]
Excuse me. I clone all the repository and run the code, finally the system reports an error (KeyError:'val_loss'), is there something wrong with the Callback? How could I solve this problem? Thanks much!

**Comment by yalickj** [comment]
I updated the file, it should be good now. As no validation data is used in training, there is no 'val_loss' in the history variable.

**Comment by GuibinChenTHU** [comment]
哇，十分感谢！我重新下载来运行一次，十分感谢

**Comment by yalickj** [comment]
> 哇，十分感谢！我重新下载来运行一次，十分感谢

不客气
