### ISSUE TITLE
North-American Utility Dataset

### ISSUE THREAD

**Issue by sulaimonwasiu** [yalickj/load-forecasting-resnet#4]
Hello,

I noticed that the North-American Utility dataset was left out in the repository for this paper. Could you please provide this dataset or give a reliable link where it can be collected.

Thank you

**Comment by yalickj** [comment]
Please find it in
https://class.ece.uw.edu/555/el-sharkawi/index_files/Page3404.htm
the dataset for the "forecasting" task is the North-American Utility dataset.
